// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions: $defaultTargetPlatform desteklenmiyor.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASVKy7u5DSOZYtZ3ikYVnVqEv3ITYHaLE',
    appId: '1:473072331709:web:2ac65616ac1bb901aa80d4',
    messagingSenderId: '473072331709',
    projectId: 'gloo-f7905',
    authDomain: 'gloo-f7905.firebaseapp.com',
    storageBucket: 'gloo-f7905.firebasestorage.app',
    measurementId: 'G-H80K78KJYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-8m-bPO7vv-7M_EHY1AitfMpPNa0HbDo',
    appId: '1:473072331709:android:5313b586fc295662aa80d4',
    messagingSenderId: '473072331709',
    projectId: 'gloo-f7905',
    storageBucket: 'gloo-f7905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB55ddtzDqtvq4BVPgCW_fWJLB_gSwbJs',
    appId: '1:473072331709:ios:57de4139590c625caa80d4',
    messagingSenderId: '473072331709',
    projectId: 'gloo-f7905',
    storageBucket: 'gloo-f7905.firebasestorage.app',
    iosBundleId: 'com.example.gloo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB55ddtzDqtvq4BVPgCW_fWJLB_gSwbJs',
    appId: '1:473072331709:ios:57de4139590c625caa80d4',
    messagingSenderId: '473072331709',
    projectId: 'gloo-f7905',
    storageBucket: 'gloo-f7905.firebasestorage.app',
    iosBundleId: 'com.example.gloo',
  );

}