// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions: $defaultTargetPlatform desteklenmiyor.',
        );
    }
  }

  static const _apiKeyWeb = String.fromEnvironment(
    'FIREBASE_API_KEY_WEB',
    defaultValue: 'AIzaSyASVKy7u5DSOZYtZ3ikYVnVqEv3ITYHaLE',
  );
  static const _apiKeyAndroid = String.fromEnvironment(
    'FIREBASE_API_KEY_ANDROID',
    defaultValue: 'AIzaSyC-8m-bPO7vv-7M_EHY1AitfMpPNa0HbDo',
  );
  static const _apiKeyIos = String.fromEnvironment(
    'FIREBASE_API_KEY_IOS',
    defaultValue: 'AIzaSyBB55ddtzDqtvq4BVPgCW_fWJLB_gSwbJs',
  );
  static const _appIdWeb = String.fromEnvironment(
    'FIREBASE_APP_ID_WEB',
    defaultValue: '1:473072331709:web:2ac65616ac1bb901aa80d4',
  );
  static const _appIdAndroid = String.fromEnvironment(
    'FIREBASE_APP_ID_ANDROID',
    defaultValue: '1:473072331709:android:bac6c3d395677a9eaa80d4',
  );
  static const _appIdIos = String.fromEnvironment(
    'FIREBASE_APP_ID_IOS',
    defaultValue: '1:473072331709:ios:3e271024cbb55d9eaa80d4',
  );
  static const _messagingSenderId = String.fromEnvironment(
    'FIREBASE_MESSAGING_SENDER_ID',
    defaultValue: '473072331709',
  );
  static const _projectId = String.fromEnvironment(
    'FIREBASE_PROJECT_ID',
    defaultValue: 'gloo-f7905',
  );
  static const _storageBucket = String.fromEnvironment(
    'FIREBASE_STORAGE_BUCKET',
    defaultValue: 'gloo-f7905.firebasestorage.app',
  );

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: _apiKeyWeb,
    appId: _appIdWeb,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    authDomain: '$_projectId.firebaseapp.com',
    storageBucket: _storageBucket,
    measurementId: 'G-H80K78KJYM',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: _apiKeyAndroid,
    appId: _appIdAndroid,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: _apiKeyIos,
    appId: _appIdIos,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
    iosBundleId: 'com.gloogame.app',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: _apiKeyIos,
    appId: '1:473072331709:ios:57de4139590c625caa80d4',
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
    iosBundleId: 'com.gloogame.app',
  );
}
